### ISSUE TITLE
Payer Address type is coded as Array 

### ISSUE THREAD

**Issue by shakerYounis** [CurrencyCloud/currencycloud-php#84]
Argument 5 passed to CurrencyCloud\Model\Payer::__construct() must be of the type array or null, string given, called in /home/vagrant/code/laravel/Lintium/vendor/currency-cloud/client/src/EntryPoint/PayersEntryPoint.php on line 47

**Comment by jonathancouchman** [comment]
Clearly the address field should be of type string and not array since this is what the json response from the api contains. Payer Entity should be updated to reflect this, however, update the Payer entity would be a breaking change for the create payment entry point, so need to consider whether to convert response to array to maintain backwards compatibility

**Comment by jonathancouchman** [comment]
Will format the response string into array to maintain backwards compatibility
https://github.com/CurrencyCloud/currencycloud-php/pull/95
